{
 "title": "Attack",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Challenged",
   "type": "stat",
   "description": "The total number of challenged IPs",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) \nand challenged = 1 \n"
    }
   ]
  },
  {
   "title": "Precision",
   "type": "gauge",
   "description": "The percentage of failed challenge IPs.Or True Positive Rate = True Positive / (True Positive + False Positive)",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--SELECT 100.0 - sum(challenge_passed) * 100.0 / sum(challenged)\n--FROM request_sets WHERE $__timeFilter(stop) \nSELECT 100.0 - 100.0*(SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) \nand challenge_passed = 1) \n/\n(SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) \nand challenged = 1 )"
    }
   ]
  },
  {
   "title": "Passed Challenge",
   "type": "stat",
   "description": "The total number of passed challenge IPs",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) \nand challenged = 1 and challenge_passed = 1"
    }
   ]
  },
  {
   "title": "Challenged",
   "type": "graph",
   "description": "The number of challenged IPs",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), target, count(distinct ip) as challenged\nFROM request_sets WHERE $__timeFilter(stop) \nand challenged = 1 \ngroup by 1, 2 order by 1"
    }
   ]
  },
  {
   "title": "Total Unique IP",
   "type": "graph",
   "description": "Total number of unique IPs",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), target, count(ip) as total\nFROM request_sets WHERE $__timeFilter(stop) \ngroup by 1,2 \norder by 1"
    }
   ]
  },
  {
   "title": "False Positives",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as false_positive\nFROM request_sets\nWHERE\n  $__timeFilter(stop) AND\n  challenged = 1 AND\n  challenge_passed = 1\nGROUP BY 1 ORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Failed challenge",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as failed_challenge\nFROM request_sets\nWHERE\n  $__timeFilter(stop) AND\n  challenged = 1 AND\n  challenge_failed > 0\nGROUP BY 1 ORDER BY 1,2"
    }
   ]
  }
 ]
}