name: "CI"
on:
  push:
    branches: [main, staging, trying]
  schedule:
    - cron: "0 0 * * SUN" # every sunday
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v20
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.10.0pre20220728_86fcd4f/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix

      - uses: cachix/cachix-action@v12
        with:
          name: gtrunsec
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run Flake Show
        run: nix -Lv flake show

      - name: Run Build MicroVM
        run: nix -Lv develop --command build-microvm

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4.4.0
      #   with:
      #     branch: gh-pages
      #     folder: ./docs/book
